package com.example.grandvns.App.Api_Connection.Properties

data class AllPropertisItem(
    val additionalrooms: String?,
    val ageofprop: String?,
    val amenities: String?,
    val area: String?,
    val area_type: String?,
    val balcony: String?,
    val buildtype: String?,
    val city: String?,
    val company_lease: String?,
    val coveredparking: String?,
    val createdby: String?,
    val createdon: String?,
    val definesize: String?,
    val defininglocation: String?,
    val description: String?,
    val explainingprice: String?,
    val explainingtheproperty: String?,
    val facing: String?,
    val floornumber: String?,
    val furnishing_status: String?,
    val lift_availability: String?,
    val loan: String?,
    val locality: String?,
    val no_of_baths: String?,
    val no_of_rooms: String?,
    val office_space_type: String?,
    val openparking: String?,
    val pantry: String?,
    val personal_washroom: String?,
    val photo: String?,
    val plotno: String?,
    val possession_status: String?,
    val powerbackup: String?,
    val price: String?,
    val projectname: String?,
    val propertyid: String?,
    val proptype: String?,
    val selectflooring: String?,
    val status: String?,
    val suitablefor: String?,
    val totalfloor: String?,
    val tower: String?,
    val unitno: String?,
    val video: String?,
    val view: String?,
)




